#!/usr/bin/env python
# coding: utf-8

# In[1]:


# https://cellphonedb.readthedocs.io/en/latest/RESULTS-DOCUMENTATION.html


# In[2]:


# METHOD 1 simple analysis (>= v1): 
# METHOD 2 statistical_analysis (>= v1)

# METHOD 3 degs_analysis (>= v3): 
# all the genes in the interaction are expressed in the corresponding cell type by more than 10% of cells (threshold = 0.1)
# at least one gene-cell type pair is in the provided DEG.tsv file.


# In[3]:


# https://github.com/ventolab/CellphoneDB/tree/master/notebooks


# In[4]:


# We then perform pairwise comparisons between all cell types. First, we randomly permute the cluster labels of all cells (1,000 default) 
# and determine the mean of the average receptor expression level in a cluster and the average ligand expression level 
# in the interacting cluster. 

# For each receptor–ligand pair in each pairwise comparison between two cell types, this generates a null distribution. 
# By calculating the proportion of the means which are equal or higher than the actual mean, 
# we obtain a p-value for the likelihood of cell-type specificity of a given receptor–ligand complex. 

# We then prioritise interactions that are highly enriched between cell types based on the number of significant pairs, 
# so that the user can manually select biologically relevant ones.


# In[ ]:





# In[5]:


# Hie et al. 2019 (PMID: 31176620). This “geometric sketching” approach aims to maintain the transcriptomic heterogeneity 
# within a dataset with a smaller subset of cells. 

# The subsampling step is optional, enabling users to perform the analysis either on all cells, 
# or with other subsampling methods of their choice.


# In[6]:


# TF activity status: CellSign module


# In[7]:


# Interaction ranking: Scoring module


# In[8]:


print("""

    To score interactions CellphoneDB v5 employs the following protocol:

    Exclude genes not participating in any interaction and those expressed in less than k% of cells within a given cell type.

    Calculate the mean expression of each gene within each cell type.

    For heteromeric proteins, aggregate the mean gene expression of each subunit employing the geometric mean.

    Scale mean gene/heteromer expression across cell types between 0 and 10.

    Calculate the product of the scale mean expression of the interaction proteins as a proxy of the interaction relevance.

    To score interactions, CellphoneDB requires log-normalized expression data, any normalisation procedure (i.e. z-scaling) 
    that transforms zeros to any other value must be avoided.

""")


# In[9]:


# Input files

# Counts file

# Meta file

# This is the file linking bacodes/cells to clusters/cell types. 
# This file is generated by the users after they have annotated each cluster identified by scRNA-seq 

# DEGs file (if needed)

# Microenvironment file (if needed)


# In[10]:


# Output files

# The “means.txt” file contains mean values for each ligand-receptor interaction (rows) for each cell-cell interaction pair (columns).

# The “pvalues.txt” contains the P values for the likelihood of cell-type specificity of a given receptor–ligand complex (rows) 
# in each cell-cell interaction pair (columns), resulting from the statistical_analysis

# The “relevant_interactions.txt” contains a binary matrix indicating if the interaction is relevant (1) or not (0). 
# An interaction is classified as relevant if a gene is a DEG in a cluster/cell type (information provided by the user 
# in the DEG.tsv file) and all the participant genes are expressed. 

# P-value (pvalues.txt), 
# Mean (means.txt), 
# Significant mean (significant_means.txt) and 
# Relevant interactions (relevant_interactions.txt)

# Deconvoluted (deconvoluted.txt)


# In[11]:


# The key files are significant_means.txt (for statistical_analysis) or 
# relevant_interactions.txt (for degs_analysis), s


# In[12]:


# Database design: input files

# 1. “gene_input”
# Mandatory fields: “gene_name”; “uniprot”; “hgnc_symbol” and “ensembl” 

# 2. “protein_input”
# Mandatory fields: “uniprot”; “protein_name” 
# Optional fields: “transmembrane”; “peripheral”; “secreted”; “receptor”; etc 


# In[13]:


# a. Location of the protein in the cell
# b. Receptors and integrins


# In[14]:


# 3. “complex_input”
# 4. “interaction_input”


# In[15]:


# Plot CellphoneDB Data: CellphoneDBViz

# https://github.com/ventolab/cellphonedbviz

# kplotspy

# https://github.com/zktuong/ktplotspy/

# https://github.com/zktuong/ktplots/ # Plotting CellPhoneDB results


# In[16]:


# https://ventolab.org/people/

# https://github.com/ventolab/CellphoneDB/tree/master/notebooks


# In[17]:


print(""" Download the database """)


# In[18]:


from IPython.display import HTML, display
from cellphonedb.utils import db_releases_utils

display(HTML(db_releases_utils.get_remote_database_versions_html()['db_releases_html_table']))


# In[19]:


import os

# -- Version of the databse
cpdb_version = 'v5.0.0'

# -- Path where the input files to generate the database are located
cpdb_target_dir = os.path.join('~/Desktop/CCI_CellPhoneDB/testdb', cpdb_version)


# In[ ]:





# In[20]:


from cellphonedb.utils import db_utils

db_utils.download_database(cpdb_target_dir, cpdb_version)


# In[ ]:





# In[ ]:





# In[ ]:




